rem passcode bezier
call del *.apk
@echo Remove APK files...
@echo Update Facebook Project Property...
call cd ./facebook-android-sdk-3.0.2/facebook
call android update project --path .
call cd ../../
call android update project --path . --name WeddingCalculator
@echo build.xml is updated...
call ant release
@echo Building in Release Mode..
call jarsigner.exe -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore bezier-release-key.keystore ./bin/WeddingCalculator-release-unsigned.apk bezier 
@echo APK is signed...
call copy /Y .\bin\WeddingCalculator-release-unsigned.apk WeddingCalculator-release-signed.apk
@echo Copy Unsigned APK to the root folder
call jarsigner.exe -verify -verbose WeddingCalculator-release-signed.apk
@echo APK is verified...
call zipalign -v 4 WeddingCalculator-release-signed.apk WeddingCalculator-release-signed-zipalign.apk
@echo zipalign APK...
call adb uninstall com.bezier.app.weddingCalculator
@echo Installed APK has been removed...
call adb install WeddingCalculator-release-signed-zipalign.apk
@echo WeddingCalculator is installed...